language: php
services: mysql

#travis usually doesn't build gh-pages branch, but we want it to for testing
#and since it is a white list we have to also whitelist everythign else
branches:
  only:
    - gh-pages
    - /^.*$/

matrix:
  fast_finish: true
  allow_failures:
  - env: BEHAT_PROFILE='osxsafari' START_SAUCE_CONNECT=true TEST_BEHAT=true
  exclude:
  - php: '5.4'
  include:
  - php: '5.4'
    env: BEHAT_PROFILE='win7ie9' START_SAUCE_CONNECT=true TEST_BEHAT=true
php:
- '5.4'
- '5.3'
env:
  global:
  - SAUCE_USERNAME="ilios"
  #SAUCE_ACCESS_KEY
  - secure: TWX+vAZYyU+m4Eur8Eyuo39feAU/8sCVqoW3QLdmP0umGSaOHxrTrQuX4lGNUOV1nLMedAQl/7FVryl4eBJwhth8iQ9xjDIdRCshN+lvQfEGB6D91FrgJ7ZoR/QnKxcHddFzaGXAlglVZE8JT5Ljp36tyKbbNoEt0YBgwSnYxW0=
  - START_LOCAL_SELENIUM=false
  - START_SAUCE_CONNECT=false
  - TEST_BEHAT=false
  - BEHAT_PROFILE=false

  matrix:
  - BEHAT_PROFILE='win7ie9' START_SAUCE_CONNECT=true TEST_BEHAT=true
  - BEHAT_PROFILE='win8ie11' START_SAUCE_CONNECT=true TEST_BEHAT=true
  - BEHAT_PROFILE='osxsafari' START_SAUCE_CONNECT=true TEST_BEHAT=true
addons:
  hosts:
  - precise64
  sauce_connect: true
before_install:
- sudo apt-get update -qq
install:
- composer install  --no-interaction -d ${TRAVIS_BUILD_DIR}

script:
- if [ "$TEST_BEHAT" = true ]; then (${TRAVIS_BUILD_DIR}/bin/behat -c
  ${TRAVIS_BUILD_DIR}/behat.yml --profile $BEHAT_PROFILE);
  fi
